/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang.pom;

import com.github.tommyettinger.idea.lang.KoboldLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class KoboldPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public KoboldPomDeclarationSearcher() {
		super(KoboldLanguage.INSTANCE);
	}
}
