/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KoboldStandaloneSetup extends KoboldStandaloneSetupGenerated {

	def static void doSetup() {
		new KoboldStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
