/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractKoboldFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "kob";

	protected AbstractKoboldFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Kobold files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Kobold";
	}

}
