/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class KoboldLanguage extends AbstractXtextLanguage {

	public static final KoboldLanguage INSTANCE = new KoboldLanguage();

	private KoboldLanguage() {
		super("com.github.tommyettinger.Kobold");
	}

}
