/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.eclipse.xtext.xbase.idea.completion.XbaseCompletionContributor;

public class AbstractKoboldCompletionContributor extends XbaseCompletionContributor {
	public AbstractKoboldCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
