/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang.psi.impl;

import com.github.tommyettinger.idea.lang.KoboldFileType;
import com.github.tommyettinger.idea.lang.KoboldLanguage;
import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class KoboldFileImpl extends BaseXtextFile {

	public KoboldFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, KoboldLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return KoboldFileType.INSTANCE;
	}
}
