/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class KoboldIdeaModule extends AbstractKoboldIdeaModule {
}
