/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class KoboldIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new KoboldStandaloneSetupIdea().createInjector
	}

}
