/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.facet;

import com.github.tommyettinger.idea.lang.KoboldLanguage;
import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class KoboldFacetType extends AbstractFacetType<KoboldFacetConfiguration> {

	public static final FacetTypeId<Facet<KoboldFacetConfiguration>> TYPEID = new FacetTypeId<Facet<KoboldFacetConfiguration>>("com.github.tommyettinger.Kobold");

	public KoboldFacetType() {
		super(TYPEID, "com.github.tommyettinger.Kobold", "Kobold");
		KoboldLanguage.INSTANCE.injectMembers(this);
	}
}
