/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KoboldAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/github/tommyettinger/idea/parser/antlr/internal/PsiInternalKobold.tokens");
	}
}
