/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang


class KoboldFileType extends AbstractKoboldFileType {
	public static final KoboldFileType INSTANCE = new KoboldFileType()
	
	new() {
		super(KoboldLanguage.INSTANCE)
	}
}
