/**
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.validation;

import com.github.tommyettinger.validation.AbstractKoboldValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KoboldValidator extends AbstractKoboldValidator {
}
