/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang.psi;

import com.github.tommyettinger.idea.lang.KoboldLanguage;
import com.intellij.psi.impl.PsiTreeChangeEventImpl;
import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class KoboldCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public KoboldCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(KoboldLanguage.INSTANCE, psiModificationTracker);
	}
	protected boolean hasJavaStructuralChanges(PsiTreeChangeEventImpl event) {
		return true;
	}

}
