/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.highlighting;

import com.github.tommyettinger.idea.lang.KoboldLanguage;
import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;

public class KoboldSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return KoboldLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
