/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractKoboldScopeProvider extends XbaseBatchScopeProvider {
}
