/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.completion

import com.github.tommyettinger.idea.lang.KoboldLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class KoboldCompletionContributor extends AbstractKoboldCompletionContributor {
	new() {
		this(KoboldLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
