/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea.lang.parser;

import com.github.tommyettinger.idea.lang.KoboldElementTypeProvider;
import com.github.tommyettinger.idea.parser.antlr.internal.PsiInternalKoboldParser;
import com.github.tommyettinger.services.KoboldGrammarAccess;
import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;

public class KoboldPsiParser extends AbstractXtextPsiParser {

	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));

	@Inject 
	private KoboldGrammarAccess grammarAccess;

	@Inject 
	private KoboldElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalKoboldParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}

	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
