/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.parser.antlr;

import com.github.tommyettinger.parser.antlr.internal.InternalKoboldParser;
import com.github.tommyettinger.services.KoboldGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KoboldParser extends AbstractAntlrParser {

	@Inject
	private KoboldGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKoboldParser createParser(XtextTokenStream stream) {
		return new InternalKoboldParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public KoboldGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KoboldGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
