/*
 * generated by Xtext 2.10.0
 */
package com.github.tommyettinger.idea;

import com.github.tommyettinger.idea.lang.KoboldLanguage;
import com.intellij.openapi.extensions.ExtensionFactory;

public class KoboldExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return KoboldLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
